flowchart LR
    A[Frontend] --> B[Streamlit]
    B --> C[Backend]
    C --> D[Python Ecosystem]
    
    D --> E1[Data Processing]
    E1 --> F1[Pandas]
    E1 --> F2[Numpy]
    
    D --> E2[ML & Analytics]
    E2 --> F3[Scikit-learn]
    E2 --> F4[XGBoost]
    
    D --> E3[Visualization]
    E3 --> F5[Plotly]
    E3 --> F6[Seaborn]
